/**
 * 공유 상수 배럴 export
 *
 * 모든 공유 상수를 단일 진입점에서 re-export한다.
 */

// 거래소 설정 상수
export {
  UPBIT_CONFIG,
  UPBIT_ENDPOINTS,
  BITHUMB_CONFIG,
  BITHUMB_ENDPOINTS,
  COINONE_CONFIG,
  COINONE_ENDPOINTS,
  EXCHANGE_CONFIGS,
  EXCHANGE_ENDPOINTS,
  SUPPORTED_EXCHANGES,
  DOMESTIC_EXCHANGES,
  FOREIGN_EXCHANGES,
  DEFAULT_CACHE_TTL_MS,
  DEFAULT_REFRESH_INTERVAL_MS,
  COINONE_POLLING_INTERVAL_MS,
  WS_MAX_RECONNECT_ATTEMPTS,
  RETRY_CONFIG,
  PREMIUM_SNAPSHOT_INTERVAL_MS,
  BINANCE_CONFIG,
  BINANCE_ENDPOINTS,
  BINANCE_PRICE_ENDPOINTS,
  BINANCE_POLLING_INTERVAL_MS,
  BYBIT_CONFIG,
  BYBIT_ENDPOINTS,
  OKX_CONFIG,
  OKX_ENDPOINTS,
  GATE_CONFIG,
  GATE_ENDPOINTS,
  BITGET_CONFIG,
  BITGET_ENDPOINTS,
} from './exchanges';

export type { ExchangeConfig, ExchangeEndpoints } from './exchanges';

// 코인 심볼 상수
export {
  MAJOR_COINS,
  MAJOR_COIN_SYMBOLS,
  DEFAULT_PREMIUM_COINS,
  BENCHMARK_SYMBOL,
  DEFAULT_CURRENCY,
  UPBIT_KRW_MARKET_PREFIX,
  DEFAULT_PREMIUM_THRESHOLD_PERCENT,
  COIN_DECIMAL_PLACES,
  DEFAULT_DECIMAL_PLACES,
  QUANTITY_DECIMAL_PLACES,
  RATE_DECIMAL_PLACES,
} from './symbols';

export type { CoinInfo } from './symbols';
