/**
 * 공유 상수 배럴 export
 *
 * 모든 공유 상수를 단일 진입점에서 re-export한다.
 */

// 거래소 설정 상수
export {
  UPBIT_CONFIG,
  UPBIT_ENDPOINTS,
  BITHUMB_CONFIG,
  BITHUMB_ENDPOINTS,
  COINONE_CONFIG,
  COINONE_ENDPOINTS,
  EXCHANGE_CONFIGS,
  EXCHANGE_ENDPOINTS,
  SUPPORTED_EXCHANGES,
  DOMESTIC_EXCHANGES,
  FOREIGN_EXCHANGES,
  DEX_EXCHANGES,
  DEFAULT_CACHE_TTL_MS,
  DEFAULT_REFRESH_INTERVAL_MS,
  COINONE_POLLING_INTERVAL_MS,
  WS_MAX_RECONNECT_ATTEMPTS,
  RETRY_CONFIG,
  PREMIUM_SNAPSHOT_INTERVAL_MS,
  BINANCE_CONFIG,
  BINANCE_ENDPOINTS,
  BINANCE_PRICE_ENDPOINTS,
  BINANCE_POLLING_INTERVAL_MS,
  BYBIT_CONFIG,
  BYBIT_ENDPOINTS,
  OKX_CONFIG,
  OKX_ENDPOINTS,
  GATE_CONFIG,
  GATE_ENDPOINTS,
  BITGET_CONFIG,
  BITGET_ENDPOINTS,
  HYPERLIQUID_CONFIG,
  HYPERLIQUID_ENDPOINTS,
  LBANK_CONFIG,
  LBANK_ENDPOINTS,
  LBANK_POLLING_INTERVAL_MS,
} from './exchanges';

export type { ExchangeConfig, ExchangeEndpoints } from './exchanges';

// 코인 심볼 상수
export {
  MAJOR_COINS,
  MAJOR_COIN_SYMBOLS,
  DEFAULT_PREMIUM_COINS,
  BENCHMARK_SYMBOL,
  DEFAULT_CURRENCY,
  UPBIT_KRW_MARKET_PREFIX,
  DEFAULT_PREMIUM_THRESHOLD_PERCENT,
  COIN_DECIMAL_PLACES,
  DEFAULT_DECIMAL_PLACES,
  QUANTITY_DECIMAL_PLACES,
  RATE_DECIMAL_PLACES,
} from './symbols';

export type { CoinInfo } from './symbols';

// 선물 거래 상수
export {
  FUTURES_EXCHANGES,
  FUTURES_DEFAULT_EXCHANGE,
  FUTURES_COINS,
  FUTURES_DEFAULT_COIN,
  FUTURES_SYMBOL_CONFIGS,
  getFuturesApiSymbol,
  getTradingViewFuturesSymbol,
} from './futures';

// 멀티 거래소 선물 대시보드 상수
export {
  EXCHANGE_COLORS,
  VALID_INDICATORS,
  SNAPSHOT_INDICATORS,
  HISTORY_INDICATORS,
  KLINE_INDICATORS,
  SESSION_RANGES,
  INDICATOR_EXCHANGE_SUPPORT,
} from './futures-dashboard';

// 마켓 스크리너 상수
export {
  COIN_MARKET_CAP_MAP,
  COIN_SECTOR_MAP,
  SECTOR_LABELS,
  COIN_NAMES,
  BULK_TICKER_CONFIGS,
  BINANCE_PREMIUM_INDEX_URL,
} from './market-screener';

// 주식-perp 비교 뷰 상수
export {
  PAIR_CONFIGS,
  DEFAULT_PAIR,
  DEFAULT_RANGE,
  RANGE_TO_INTERVAL,
  KRX_SESSION,
} from './stock-perp';
